trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  solutionPath: 'OmniFlow/OmniFlow.sln'
  projectPath: 'OmniFlow/OmniFlow.WebApi/OmniFlow.WebApi.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore solution'
  inputs:
    command: 'restore'
    projects: '$(solutionPath)'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solutionPath)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Test solution'
  inputs:
    command: 'test'
    projects: '$(solutionPath)'
    arguments: '--configuration $(buildConfiguration) --no-build --logger trx'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'OmniFlow-Azure-Conn'
    WebAppName: 'omniflow-backend'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
