// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniFlow.Infrastructure.Contexts;

#nullable disable

namespace OmniFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316181047_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<List<string>>("Mentions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("mentions");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("upvote_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "PostId")
                        .HasName("uq_comments_id_post_id");

                    b.HasIndex("Mentions")
                        .HasDatabaseName("idx_comments_mentions_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Mentions"), "gin");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.HasIndex("ParentCommentId", "PostId");

                    b.ToTable("comments", null, t =>
                        {
                            t.HasCheckConstraint("valid_content", "length(content) > 0");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.CommentUpvote", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CommentId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_comment_upvotes_user_id");

                    b.ToTable("comment_upvotes", (string)null);
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.CommunityTip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("upvote_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId");

                    b.HasIndex("TripId", "UserId")
                        .HasDatabaseName("idx_community_tips_visible")
                        .HasFilter("deleted_at IS NULL AND is_visible = TRUE");

                    b.ToTable("community_tips", null, t =>
                        {
                            t.HasCheckConstraint("valid_content", "length(content) > 0");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("airline");

                    b.Property<DateTime>("ArrivalAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("arrival_at");

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<string>("BookingReference")
                        .HasColumnType("text")
                        .HasColumnName("booking_reference");

                    b.Property<string>("CabinClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cabin_class");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<DateTime>("DataFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fetched_at");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<DateTime>("DepartureAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("departure_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("FlightDirection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flight_direction");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flight_number");

                    b.Property<string>("FromAirport")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_airport");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_city");

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_booked");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_direct");

                    b.Property<Guid?>("ItineraryGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_group_id");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_person");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ToAirport")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_airport");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_city");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("total_price");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryGroupId")
                        .HasDatabaseName("idx_flights_itinerary_group");

                    b.HasIndex("TripId");

                    b.ToTable("flights", null, t =>
                        {
                            t.HasCheckConstraint("booked_consistency", "is_booked = FALSE OR booked_at IS NOT NULL");

                            t.HasCheckConstraint("booking_ref_requires_is_booked", "booking_reference IS NULL OR is_booked = TRUE");

                            t.HasCheckConstraint("iata_from_airport", "from_airport ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("iata_to_airport", "to_airport ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("valid_duration", "duration_minutes > 0");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Follow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid")
                        .HasColumnName("following_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId")
                        .HasDatabaseName("idx_follows_following_id");

                    b.ToTable("follows", null, t =>
                        {
                            t.HasCheckConstraint("no_self_follow", "follower_id != following_id");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<string>("BookingReference")
                        .HasColumnType("text")
                        .HasColumnName("booking_reference");

                    b.Property<bool>("BreakfastIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("breakfast_included");

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cancellation_policy");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("check_in");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("check_out");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<DateTime>("DataFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fetched_at");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<string>("HotelAddress")
                        .HasColumnType("text")
                        .HasColumnName("hotel_address");

                    b.Property<double?>("HotelLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("hotel_latitude");

                    b.Property<double?>("HotelLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("hotel_longitude");

                    b.Property<string>("HotelName")
                        .HasColumnType("text")
                        .HasColumnName("hotel_name");

                    b.Property<string>("HotelPhone")
                        .HasColumnType("text")
                        .HasColumnName("hotel_phone");

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_booked");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("numeric")
                        .HasColumnName("price_per_night");

                    b.Property<string>("ProviderUrl")
                        .HasColumnType("text")
                        .HasColumnName("provider_url");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_type");

                    b.Property<int?>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("total_price");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripId");

                    b.ToTable("hotels", null, t =>
                        {
                            t.HasCheckConstraint("booked_consistency", "is_booked = FALSE OR booked_at IS NOT NULL");

                            t.HasCheckConstraint("place_or_hotel_name", "place_id IS NOT NULL OR hotel_name IS NOT NULL");

                            t.HasCheckConstraint("valid_dates", "check_out > check_in");

                            t.HasCheckConstraint("valid_stars", "stars IS NULL OR (stars >= 1 AND stars <= 5)");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.KarmaEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("UserId", "SourceId", "EventType")
                        .IsUnique()
                        .HasDatabaseName("idx_karma_publish_unique")
                        .HasFilter("event_type = 'TripPublished'");

                    b.HasIndex("UserId", "SourceId", "EventType", "ActorId")
                        .IsUnique()
                        .HasDatabaseName("idx_karma_interaction_unique")
                        .HasFilter("event_type != 'TripPublished'");

                    b.ToTable("karma_events", null, t =>
                        {
                            t.HasCheckConstraint("source_consistency", "source_type IS NULL OR source_id IS NOT NULL");

                            t.HasCheckConstraint("valid_event_source_type", "(event_type IN ('TripPublished', 'TripForked', 'TripUpvoted') AND source_type = 'Trip') OR (event_type = 'PostUpvoted' AND source_type = 'Post') OR (event_type = 'TipUpvoted' AND source_type = 'Tip')");

                            t.HasCheckConstraint("valid_points", "points != 0");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_notifications_unread")
                        .HasFilter("is_read = FALSE");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("follow_has_no_target", "notification_type != 'Follow' OR (target_id IS NULL AND target_type IS NULL)");

                            t.HasCheckConstraint("read_consistency", "is_read = FALSE OR read_at IS NOT NULL");

                            t.HasCheckConstraint("valid_notification_target_type", "(notification_type = 'Follow') OR (notification_type IN ('PostUpvote', 'Comment', 'Mention') AND target_type = 'Post') OR (notification_type = 'CommentUpvote' AND target_type = 'Comment') OR (notification_type = 'TipUpvote' AND target_type = 'Tip') OR (notification_type IN ('TripUpvote', 'Fork') AND target_type = 'Trip')");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<List<int>>("BestMonths")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("best_months");

                    b.Property<string[]>("BudgetTiers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("budget_tiers");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<decimal>("EstimatedPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("estimated_price");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("text")
                        .HasColumnName("google_place_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_hours");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<string[]>("TravelStyles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("travel_styles");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("BestMonths")
                        .HasDatabaseName("idx_places_best_months_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BestMonths"), "gin");

                    b.HasIndex("BudgetTiers")
                        .HasDatabaseName("idx_places_budget_tiers_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BudgetTiers"), "gin");

                    b.HasIndex("City")
                        .HasDatabaseName("idx_places_city")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("OpeningHours")
                        .HasDatabaseName("idx_places_opening_hours_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OpeningHours"), "gin");

                    b.HasIndex("TravelStyles")
                        .HasDatabaseName("idx_places_travel_styles_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TravelStyles"), "gin");

                    b.ToTable("places", null, t =>
                        {
                            t.HasCheckConstraint("free_has_zero_price", "NOT is_free OR estimated_price = 0");

                            t.HasCheckConstraint("valid_best_months", "best_months IS NULL OR best_months <@ ARRAY[1,2,3,4,5,6,7,8,9,10,11,12]");

                            t.HasCheckConstraint("valid_rating", "rating IS NULL OR (rating >= 1 AND rating <= 5)");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<string>>("AiTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ai_tags");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("CommentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("comment_count");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<double?>("LocationLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("location_latitude");

                    b.Property<double?>("LocationLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("location_longitude");

                    b.Property<List<string>>("Photos")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("photos");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_type");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("upvote_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AiTags")
                        .HasDatabaseName("idx_posts_ai_tags_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AiTags"), "gin");

                    b.HasIndex("PlaceId");

                    b.HasIndex("Tags")
                        .HasDatabaseName("idx_posts_tags_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_posts_visible")
                        .HasFilter("deleted_at IS NULL AND is_visible = TRUE");

                    b.ToTable("posts", null, t =>
                        {
                            t.HasCheckConstraint("content_or_photo", "content IS NOT NULL OR cardinality(photos) > 0");

                            t.HasCheckConstraint("non_negative_counts", "upvote_count >= 0 AND comment_count >= 0");

                            t.HasCheckConstraint("route_requires_trip", "post_type != 'Route' OR trip_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.PostUpvote", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("PostId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_post_upvotes_user_id");

                    b.ToTable("post_upvotes", (string)null);
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceFingerprint")
                        .HasColumnType("text")
                        .HasColumnName("device_fingerprint");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("idx_refresh_tokens_hash_active")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_active")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("valid_expiry", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.SavedTrip", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "TripId");

                    b.HasIndex("TripId")
                        .HasDatabaseName("idx_saved_trips_trip_id");

                    b.ToTable("saved_trips", (string)null);
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Stop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActivityPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("activity_price");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("added_by");

                    b.Property<string>("AiReasoning")
                        .HasColumnType("text")
                        .HasColumnName("ai_reasoning");

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("arrival_time");

                    b.Property<string>("BookingReference")
                        .HasColumnType("text")
                        .HasColumnName("booking_reference");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<string>("CustomCategory")
                        .HasColumnType("text")
                        .HasColumnName("custom_category");

                    b.Property<double?>("CustomLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("custom_latitude");

                    b.Property<double?>("CustomLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("custom_longitude");

                    b.Property<string>("CustomName")
                        .HasColumnType("text")
                        .HasColumnName("custom_name");

                    b.Property<string>("CustomPhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("custom_photo_url");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid?>("FallbackPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("fallback_place_id");

                    b.Property<bool>("IsTimeLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_time_locked");

                    b.Property<bool>("IsVisited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_visited");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<double>("OrderIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("order_index");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("ReservationNote")
                        .HasColumnType("text")
                        .HasColumnName("reservation_note");

                    b.Property<string>("TransportFromPrevious")
                        .HasColumnType("text")
                        .HasColumnName("transport_from_previous");

                    b.Property<decimal>("TransportPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("transport_price");

                    b.Property<int?>("TravelTimeFromPrevious")
                        .HasColumnType("integer")
                        .HasColumnName("travel_time_from_previous");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("VisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visited_at");

                    b.HasKey("Id");

                    b.HasIndex("FallbackPlaceId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripId", "DayNumber", "OrderIndex")
                        .HasDatabaseName("idx_stops_trip_day_order");

                    b.ToTable("stops", null, t =>
                        {
                            t.HasCheckConstraint("ai_reasoning_required", "added_by != 'Ai' OR ai_reasoning IS NOT NULL");

                            t.HasCheckConstraint("custom_place_requires_category", "custom_name IS NULL OR custom_category IS NOT NULL");

                            t.HasCheckConstraint("fallback_differs_from_place", "fallback_place_id IS NULL OR fallback_place_id != place_id");

                            t.HasCheckConstraint("place_or_custom_name", "place_id IS NOT NULL OR custom_name IS NOT NULL");

                            t.HasCheckConstraint("time_lock_requires_arrival", "is_time_locked = FALSE OR arrival_time IS NOT NULL");

                            t.HasCheckConstraint("visited_consistency", "is_visited = FALSE OR visited_at IS NOT NULL");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.TipUpvote", b =>
                {
                    b.Property<Guid>("TipId")
                        .HasColumnType("uuid")
                        .HasColumnName("tip_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("TipId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_tip_upvotes_user_id");

                    b.ToTable("tip_upvotes", (string)null);
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BudgetTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("budget_tier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("CoverPhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_photo_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<int>("ForkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("fork_count");

                    b.Property<Guid?>("ForkedFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("forked_from_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("PersonCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("person_count");

                    b.Property<decimal>("PopularityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("popularity_score");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TravelStyle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("travel_style");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("upvote_count");

                    b.Property<decimal?>("UserBudget")
                        .HasColumnType("numeric")
                        .HasColumnName("user_budget");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("ForkedFromId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_trips_explore")
                        .HasFilter("status = 'Published' AND deleted_at IS NULL");

                    b.HasIndex("Tags")
                        .HasDatabaseName("idx_trips_tags_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.ToTable("trips", null, t =>
                        {
                            t.HasCheckConstraint("non_negative_counts", "fork_count >= 0 AND upvote_count >= 0 AND view_count >= 0");

                            t.HasCheckConstraint("valid_dates", "end_date >= start_date");

                            t.HasCheckConstraint("valid_person_count", "person_count >= 1");
                        });
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.TripUpvote", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("TripId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_trip_upvotes_user_id");

                    b.ToTable("trip_upvotes", (string)null);
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<int>("FollowersCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("followers_count");

                    b.Property<int>("FollowingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("following_count");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_suspended");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<int>("KarmaScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("karma_score");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_photo_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email_unique")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username_unique")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("non_negative_follow_counts", "followers_count >= 0 AND following_count >= 0");

                            t.HasCheckConstraint("username_format", "username ~ '^[a-zA-Z0-9_]{3,30}$'");
                        });
                });

            modelBuilder.Entity("OmniFlow.Infrastructure.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(256)
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OmniFlow.Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OmniFlow.Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniFlow.Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OmniFlow.Infrastructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Comment", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniFlow.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId", "PostId")
                        .HasPrincipalKey("Id", "PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.CommentUpvote", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.CommunityTip", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniFlow.Domain.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Flight", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Trip", "Trip")
                        .WithMany("Flights")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Follow", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniFlow.Domain.Entities.User", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Hotel", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniFlow.Domain.Entities.Trip", "Trip")
                        .WithMany("Hotels")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.KarmaEvent", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Notification", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Post", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniFlow.Domain.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniFlow.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.PostUpvote", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.SavedTrip", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Stop", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Place", "FallbackPlace")
                        .WithMany()
                        .HasForeignKey("FallbackPlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniFlow.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniFlow.Domain.Entities.Trip", "Trip")
                        .WithMany("Stops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FallbackPlace");

                    b.Navigation("Place");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.TipUpvote", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.CommunityTip", null)
                        .WithMany()
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Trip", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("ForkedFromId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmniFlow.Domain.Entities.User", "Owner")
                        .WithMany("Trips")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.TripUpvote", b =>
                {
                    b.HasOne("OmniFlow.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.User", b =>
                {
                    b.HasOne("OmniFlow.Infrastructure.Models.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("OmniFlow.Domain.Entities.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("Hotels");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("OmniFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Posts");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
